// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSZ76feIPi6QajXaHtKFhGJZ-5L6l1V_s',
    appId: '1:752838498547:web:208cca48dab7bc3f1dbf86',
    messagingSenderId: '752838498547',
    projectId: 'wallpapers-app1',
    authDomain: 'wallpapers-app1.firebaseapp.com',
    storageBucket: 'wallpapers-app1.appspot.com',
    measurementId: 'G-3CN5GZDRLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL109cnE2bkl2x5U7zZqS3nCY3SwixUsQ',
    appId: '1:752838498547:android:7e71ea324350ff021dbf86',
    messagingSenderId: '752838498547',
    projectId: 'wallpapers-app1',
    storageBucket: 'wallpapers-app1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOeadsYIpVl2WyrUROkguhqO68o1q_VS4',
    appId: '1:752838498547:ios:ddd7f54d34c8bbf01dbf86',
    messagingSenderId: '752838498547',
    projectId: 'wallpapers-app1',
    storageBucket: 'wallpapers-app1.appspot.com',
    iosBundleId: 'com.example.wallpaperapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOeadsYIpVl2WyrUROkguhqO68o1q_VS4',
    appId: '1:752838498547:ios:fe7cade827aeb3ce1dbf86',
    messagingSenderId: '752838498547',
    projectId: 'wallpapers-app1',
    storageBucket: 'wallpapers-app1.appspot.com',
    iosBundleId: 'com.example.wallpaperapp.RunnerTests',
  );
}
